language: php

php:
  - 5.6

env:
  - EXTJS_VERSION_WITHOUT_COMMENTS=5.0.0
  - EXTJS_VERSION=4.2.1
  - EXTJS_VERSION=4.2.0
  - EXTJS_VERSION_LEGACY=4.1.1a
  - EXTJS_VERSION_LEGACY=4.1.0
  - EXTJS_VERSION_LEGACY=4.0.7

matrix:
  fast_finish: true

branches:
  only:
    - master

before_script:
  # prepare the jasmine tests
  - cd tests/lib
  - if [ $EXTJS_VERSION_WITHOUT_COMMENTS ]; then wget http://cdn.sencha.io/ext/gpl/$EXTJS_VERSION_WITHOUT_COMMENTS/build/ext-all-debug.js -O ext-all-debug-w-comments.js ; fi
  - if [ $EXTJS_VERSION ]; then wget http://cdn.sencha.io/ext/gpl/$EXTJS_VERSION/ext-all-debug-w-comments.js ; fi
  - if [ $EXTJS_VERSION_LEGACY ]; then wget http://cdn.sencha.io/ext-$EXTJS_VERSION_LEGACY-gpl/ext-all-debug-w-comments.js ; fi
  - cd ../../

  # get pahntomjs for jasmine
  - wget https://raw.github.com/mark-rushakoff/OpenPhantomScripts/master/phantom-jasmine.js

script:
  # execute the jasmine tests for Ext JS
  - if [[ $EXTJS_VERSION || $EXTJS_VERSION_LEGACY || $EXTJS_VERSION_WITHOUT_COMMENTS ]]; then phantomjs phantom-jasmine.js tests/SpecRunner.html ; fi

notifications:
  email:
    recipients:
      - mail@banchaproject.org
